plt.close('all')
fig, ax = plt.subplots()
im = ax.imshow(outsoma, cmap=plt.cm.RdBu, vmin=np.min(outsoma), vmax=np.max(outsoma), extent=[min(distlist), max(distlist), min(durlist), max(durlist)], aspect = 'auto')
im.set_interpolation('none')
cb = fig.colorbar(im, ax=ax)
plt.xlabel('Electrode Distance along cell [microns]')
plt.ylabel('Pulse duration [ms]')
plt.title('Threshold vs. DPP Location and Duration (Soma)')
plt.show()
